### PR TITLE
Refactor some container methods

### PR DESCRIPTION
**Pull request by joseph-wortmann**
- escape and unescape moved to utils.py
- added create_xxx methods to Segment, Field, Repetition and Component
- added extract_field and assign_field to Segment to allow working with Segments in an easier way
- updated Message.create_ack to use new Segment methods

### CODE REVIEW

**Comment by joseph-wortmann** [comment]
This needs more work. Sorry.

**Comment by johnpaulett** [comment]
@joseph-wortmann no worries. Feel free to open a draft PR if you need actions to run, and squash prior  to submitting.

**Comment by joseph-wortmann** [comment]
Sorry again - one more change

**Comment by joseph-wortmann** [comment]
There. I think that this is finally clean. @johnpaulett let me know what you think. Should be fully backwards compatible (with the minor exception of the `_ParsePlan` constructor, which no one should be using directly anyhow).

**Pull request merged**
