### PR TITLE
Make ishl7() robust against MSH appearing in legitimate values.

### PR DESCRIPTION
**Pull request by rectalogic**
Fixes https://github.com/johnpaulett/python-hl7/issues/39

### CODE REVIEW

**Comment by johnpaulett** [comment]
Looks good to me. @joseph-wortmann any concerns given the change you had implemented for `ishl7`?

**Comment by joseph-wortmann** [comment]
> Looks good to me. @joseph-wortmann any concerns given the change you had implemented for `ishl7`?

@johnpaulett @rectalogic 

I actually didn't modify or create that function. 

That said, the change proposed will have an issue if an HL7 message creator changes the field separator character. This is technically HL7 legal, but I have (almost) never seen someone do that.

It's really your call as to the PR - that function is never used within the framework, and if you approve it the likelihood that it will have an issue in the field is next to 0.

**Comment by rectalogic** [comment]
I pushed a fix to deal with non-standard field separator

**Comment by rectalogic** [comment]
We're still pinned at 0.4.1 since we can't use 0.4.2 - any chance this can be merged?

**Comment by joseph-wortmann** [comment]
@johnpaulett I think that we should merge this for @rectalogic and cut a release. I reviewed again and it looks fine.

@rectalogic I apologize if I was the holdup. Thanks for bringing this back to the top of mind.

**Comment by johnpaulett** [comment]
v0.4.3 released -- thanks @rectalogic and @joseph-wortmann

**Pull request merged**
