### PR TITLE
Fixes escaping of ASCII chars

### LINKED ISSUE #14: Buggy ASCII escaping
If you escape a string containing any ASCII characters, this will lead to a `TypeError`:

``` python
import hl7

msg = hl7.Message(separator='\r', separators='\r|^~\&')
msg.escape('asdf')
```

``` plain
Traceback (most recent call last):
  File "hl7/__init__.py", line 630, in escape
    return ''.join(rv)
TypeError: sequence item 0: expected str instance, bytes found
```

### PR DESCRIPTION
**Pull request by f3anaro**
Fixes #14 by not encoding ASCII chars. Adds additional tests.

### CODE REVIEW

**Comment by f3anaro** [comment]
*Bump*

**Comment by Myeongchan-Kim** [comment]
I had the same problem. I think it worked on Python2 because it implicitly changed `byte`->`str`, but doesn't works on Python3. thank you @f3anaro !
Please merge this PR ASAP!

**Comment by f3anaro** [comment]
Hey @Myeongchan-Kim :) If you are interessted in HL7 handling in Python, I can recommend https://github.com/crs4/hl7apy. It is more Pythonic IMHO.

**Comment by johnpaulett** [comment]
@Myeongchan-Kim What character was causing you an issue?  Can you share what field this character was occurring in?

**Comment by f3anaro** [comment]
> @Myeongchan-Kim What character was causing you an issue? Can you share what field this character was occurring in?

Maybe my example in #14 helps?

**Comment by Myeongchan-Kim** [comment]
@johnpaulett , it was just `'999'`. it converted into `[b'9', b'9', b'9']` then made error when `''.join(rv)`. Python 3 doesn't convert auto-type conversion between `byte` -> `str`.

**Comment by Myeongchan-Kim** [comment]
@f3anaro Yeah, your codes helps a lot Thanks!

**Comment by johnpaulett** [comment]
Thank you @f3anaro for this fix -- I apologize it took this long.  

I'm looking at adding some type hints and may cut a 0.4.0 with that.

**Comment by johnpaulett** [comment]
Released 0.3.5 that includes this fix.  Working on some more items that will be part of 0.4.0

**Pull request merged**
